test = [
    "Serviços",
    "Buscar serviços por",
    "Categorias",
    "Órgãos",
    "Estados",
    "Serviços por público alvo",
    "Cidadãos",
    "Empresas",
    "Órgãos e Entidades Públicas",
    "Demais segmentos (ONGs, organizações sociais, etc)",
    "Servidor Público",
    "Galeria de Aplicativos",
    "Notícias",
    "Serviços para o cidadão",
    "Saúde",
    "Agricultura e Pecuária",
    "Cidadania e Assistência Social",
    "Cultura e Esporte",
    "Economia e Gestão Pública",
    "Educação e Pesquisa",
    "Energia",
    "Forças Armadas e Defesa Civil",
    "Infraestrutura",
    "Justiça e Segurança",
    "Meio Ambiente",
    "Trabalho e Previdência",
    "Turismo",
    "Acompanhe o Planalto",
    "Navegação",
    "Acessibilidade",
    "Mapa do Site",
    "Termos de Uso",
    "Sobre o gov.br",
    "Acesse sua conta gov.br",
    "Órgãos do Governo",
    "Temas em Destaque",
    "Por dentro do Gov.br",
    "Dúvidas Frequentes em relação ao Portal gov.br",
    "Dúvidas Frequentes da conta gov.br",
    "Ajuda para Navegar o Portal",
    "Conheça os elementos do Portal",
    "Política de e-participação",
    "Termos de Uso",
    "Governo Digital",
    "Guia de Edição de Serviços do Portal Gov.br",
    "Dados do Governo Federal",
    "Dados Abertos",
    "Painel Estatístico de Pessoal",
    "Painel de Compras do Governo Federal",
    "Acesso à Informação",
    "Redefinir Cookies",
    "Redes sociais",
    "Todo o conteúdo deste site está publicado sob a licença Creative Commons Atribuição-SemDerivações 3.0 Não Adaptada.",
]
